Models/Seed.cs
using System;
using System.Security.Policy;

namespace Tracker.Models
{
    public class Seed
    {
        public int Id { get; set; }

        public string? Name { get; set; }

        public string? WaterSchedule { get; set; }
        //public string? WaterTime { get; set; }

        public string? HardinessZone { get; set; }

        public virtual ICollection<SeedWaterBed>? SeedWaterBed { get; set; }

        public Seed(string name, string hardinessZone, string waterSchedule)
        {
            Name = name;
            //Beds = new List<Bed>();
            HardinessZone = hardinessZone;
            WaterSchedule = waterSchedule;
            //WaterTime = ConvertWaterToTime();
            SeedWaterBed = new HashSet<SeedWaterBed>();

        }
        public Seed()
        {
            SeedWaterBed = new HashSet<SeedWaterBed>();
        }

        //public string ConvertWaterToTime()
        //{
        //    //    ////if (waterSchedule == null || datePlanted == null )
        //    //    ////{
        //    //    ////    return null;
        //    //    //}

        //    //foreach (SeedWaterBed waterBed in SeedWaterBed)
        //    {

        //        if (WaterSchedule == "1")
        //        {
        //            WaterTime = "604800000";
        //            //DatePlanted.AddDays(7);
        //        }
        //        else if (WaterSchedule == "2")
        //        {
        //            WaterTime = "259200000";
        //            //DatePlanted.AddDays(3);
        //        }
        //        else if (WaterSchedule == "3")
        //        {
        //            WaterTime = "1209600000";
        //            //DatePlanted.AddDays(14);
        //        }
        //        else if (WaterSchedule == "4")
        //        {
        //            WaterTime = "10000";
        //            //DatePlanted.AddSeconds(10);
        //        }
        //    }
        //    return (WaterTime);
        //    }

}
}

Controllers/BedController.cs
using System;
using System.Security.Cryptography.X509Certificates;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Tracker.Models;
using Tracker.ViewModels;
using Tracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.CodeAnalysis.VisualBasic.Syntax;

namespace Tracker.Controllers
{
    public class BedController : Controller
    {
        private TrackerDbContext context;

        public BedController(TrackerDbContext dbContext)
        {
            context = dbContext;
        }
        [HttpGet]
        public IActionResult Index()
        {
            List<Bed> beds = context.Beds.ToList();
            return View(beds);
        }

        [HttpGet]
        public IActionResult Add()
        {
            AddBedViewModel bed = new AddBedViewModel();
            return View(bed);
        }

        [HttpPost]
        public IActionResult AddBed(AddBedViewModel viewModel)
        {
            if (ModelState.IsValid)
                    {
                Bed newBed = new Bed
                {
                    Name = viewModel.Name,
                    //IsItTime = viewModel.IsItTime

                };
                    

                context.Beds.Add(newBed);
                      
                context.SaveChanges();

                return Redirect("/Bed/");
            }
            return View("Add", viewModel);
        }

        //[HttpGet]
        //public IActionResult AddBedToWater(int id)
        //{
        //    Water theWater = context.Waters.Find(id);

        //    List<Bed> possibleBeds = context.Beds.ToList();

        //    AddBedViewModel viewModel = new AddBedViewModel(theWater, possibleBeds);
        //    return View(viewModel);
        //}

        //[HttpPost]
        //public IActionResult ProcessAddBedToSeed(AddBedViewModel viewModel)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        int bedId = viewModel.BedId;
        //        int seedId = viewModel.SeedId;

        //        //access seeds property in bed table and look for bedId that matches the one selected
        //        //access seeds table and selected seed
        //        //if seed already has a relationship with bed it won't be found and won't be added
        //        Bed theBed = context.Beds.Include(b=>b.Seeds).Where(b => b.Id == bedId).First();
        //        Seed theSeed = context.Seeds.Where(s => s.Id == seedId).First();


        //            theSeed.Beds.Add(theBed);

        //            context.SaveChanges();



        //        return Redirect("/Seed/Detail/" + seedId);
        //    }
        //    return View(viewModel);

        //}
        public IActionResult Delete()
        {
            ViewBag.beds = context.Beds.ToList();

            return View();
        }

        [HttpPost]
        public IActionResult DeleteBed(int[] bedIds)
        {
            foreach (int bedId in bedIds)
            {
                Bed theBed = context.Beds.Find(bedId);
                context.Beds.Remove(theBed);
            }

            context.SaveChanges();

            return Redirect("/Bed");
        }

        public IActionResult Detail(int id)
        {
            Bed theBed = context.Beds
            .Include(j => j.SeedWaterBed).ThenInclude(a => a.Seed)
            .Include(j => j.SeedWaterBed).ThenInclude(a => a.Water)
            .Single(j => j.Id == id);


            //Load THE SEEDS on the view model

            BedDetailViewModel viewModel = new BedDetailViewModel(theBed);

            return View(viewModel);
        }
    }
}
      

Controllers/SeedController.cs
using System;
using System.Security.Cryptography.X509Certificates;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Tracker.Models;
using Tracker.ViewModels;
using Tracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Tracker.Controllers
{
    public class SeedController : Controller
    {
        private TrackerDbContext context;


        public SeedController(TrackerDbContext dbContext, ILogger<SeedController> logger)
        {
            context = dbContext;
        }


        public IActionResult Index()
        {
            List<Seed> seeds = context.Seeds.ToList();
            //List<Seed> seeds = context.Seeds.ToList();
            return View(seeds);
        }

        [HttpGet]
        public IActionResult Add()
        {
            AddSeedViewModel seed = new AddSeedViewModel();
            return View(seed);
        }

        [HttpPost]
        public IActionResult Add(AddSeedViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Seed newSeed = new Seed
                {
                    Name = viewModel.Name,
                    WaterSchedule = viewModel.WaterSchedule,
                    HardinessZone = viewModel.HardinessZone,
                    //    WaterTime = viewModel.WaterTime,
                };

                context.Seeds.Add(newSeed);
                context.SaveChanges();

                return Redirect("/Seed/");
            }

            return View("Add", viewModel);
        }

        [HttpGet]
        public IActionResult AddWater(int id)
        {
            Bed? theBed = context.Beds.First(a => a.Id == id);
            List<Seed> possibleSeeds = context.Seeds.ToList();

            AddWaterSeedToBedViewModel viewModel = new AddWaterSeedToBedViewModel(theBed, possibleSeeds);
            return View("AddSeedToWater", viewModel);
        }

        [HttpPost]
        public IActionResult AddWater(AddWaterSeedToBedViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                int waterId = viewModel.WaterId;
                int seedId = viewModel.SeedId;
                int bedId = viewModel.BedId;

                Water theWater = context.Waters.Include(p => p.SeedWaterBed).Where(e => e.Id == waterId).First();
                Seed theSeed = context.Seeds.Where(s => s.Id == seedId).First();
                Bed bed = context.Beds.First(s => s.Id == bedId);

                theWater.SeedWaterBed.Add(new SeedWaterBed
                {
                    BedId = bedId,
                    SeedId = seedId,
                    WaterId = waterId
                });
                context.SaveChanges();
                return Redirect("Bed/Detail" + waterId);
            }

            return View(viewModel);
        }


        public IActionResult Delete()
        {
            ViewBag.seeds = context.Seeds.ToList();

            return View();
        }

        [HttpPost]
        public IActionResult DeleteSeed(int[] seedIds)
        {
            foreach (int seedId in seedIds)
            {
                Seed theSeed = context.Seeds.Find(seedId);
                context.Seeds.Remove(theSeed);
            }

            context.SaveChanges();

            return Redirect("/Seed");
        }


        public IActionResult Detail(int id)
        {
            Seed theSeed = context.Seeds.First(j => j.Id == id);

            SeedDetailViewModel viewModel = new SeedDetailViewModel(theSeed);

            return View(viewModel);
        }
    }
}

Controllers/WaterController.cs
using Microsoft.AspNetCore.Mvc;
using Tracker.Data;
using Tracker.Models;
using Tracker.ViewModels;

//using Microsoft.Software.Form;


namespace Tracker.Controllers
{
    public class WaterController : Controller
    {
        private TrackerDbContext Context;

        public WaterController(TrackerDbContext context)
        {
            Context = context;
        }


        public IActionResult Index()
        {
            List<Water> water = Context.Waters.ToList();
            //for (int i = 0; i < water.Count; i++)
            //{
            //    Seed theSeed = seed[i];

            //    if (theSeed.NeedsWater.Equals(DateTime.Now))
            //    {
            //        //put this i a viewbag and add message: DO THIS IN THE DOM IN JAVASCRIPT
            //    };
            //}

            return View("../Seed/Index"); // TODO: Fix
        }

        public IActionResult Add()
        {
            Water water = new Water();
            return View("../Seed/Index"); // TODO: Fix
        }

        [HttpGet]
        public IActionResult AddWaterSeedToBed(int id)
        {
            Bed theBed = Context.Beds.Find(id);
            List<Water> possibleWaters = Context.Waters.ToList();

            AddWaterSeedToBedViewModel viewModel = new AddWaterSeedToBedViewModel(theBed, possibleWaters);

            return View("../Seed/Index"); // TODO: Fix
        }

        [HttpPost]
        public IActionResult Add(Water water)
        {
            if (ModelState.IsValid)
            {
                Context.Waters.Add(water);

                Context.SaveChanges();
                return Redirect("Bed/Detail");
            }

            return View("../Seed/AddSeedToWater", new AddWaterSeedToBedViewModel());  // TODO: Fix
        }


        [HttpPost]
        public IActionResult AddWaterSeedToBed(AddWaterSeedToBedViewModel viewModel)
        {
            //this is unfinished, im confused on how to connect seed and bed to the water id
            if (ModelState.IsValid)
            {
        
        
                int bedId = viewModel.BedId;
                
                Bed theBed = Context.Beds.First(t => t.Id == bedId);
                Seed selectedSeed = Context.Seeds.First(a => a.Id == viewModel.SeedId);

                // Add water
                Context.Waters.Add(new Water
                {
                    Bedname = theBed.Name,
                    DatePlanted = viewModel.DatePlanted,
                    Seedname = selectedSeed.Name,
              
                });
                Context.SaveChanges();

                // Add seed water bed
                Water water = Context.Waters.OrderByDescending(a => a.Id).First();
        
                theBed.SeedWaterBed.Add(new SeedWaterBed
                {
                    BedId = theBed.Id,
                    SeedId = selectedSeed.Id,
                    WaterId = water.Id
                });


                //I NEED TO CALL THIS FUNCTION SOMEHWERE BUT WHERE?!

                //if (IsItTime())
                //{
                //    ViewBag.NeedsWaterAlert = true;
                //}



                Context.SaveChanges();
                return Redirect("~/Bed/Detail/" + bedId);
        
            }

            return View("../Seed/AddSeedToWater");
        
        }
    }
}

Views/Seed/Add.cshtml
@model Tracker.Models.Seed
@using Microsoft.AspNetCore.Identity

@inject UserManager<IdentityUser> UserManager

<h1>Add Seed</h1>
<body style="background-color: #D1CA08 ">
    <form asp-controller="Seed" asp-action="AddSeed" method="post">
        <div class="form-group">
            <label asp-for="Name">Name</label>
            <input asp-for="Name" class="form-control" />
            <span></span>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="DatePlanted">Date Watered</label>
            <input asp-for="DatePlanted" class="form-control" />
            <span></span>
            <span asp-validation-for="DatePlanted" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="HardinessZone">Hardiness Zone</label>
            <input asp-for="HardinessZone" class="form-control" />
            <span></span>
            <span asp-validation-for="HardinessZone" style="color:red"></span>
        </div>

        <br />
        @*<div class="form-group">
                <label asp-for="ZipCode">Zipcode</label>
                <input asp-for="ZipCode" class="form-control" />
                <span></span>
            </div>*@

        <div class="form-group">
            @*<label asp-for="UserId"></label>*@
            <input type="hidden" asp-for="UserId" class="form-control" value="@UserManager.GetUserId(User)" />
            <span></span>
        </div>
        <br />

        <div class="form-group">
            <label asp-for="WaterSchedule">Watering Schedule</label>
            <select asp-for="WaterSchedule">
                <option value="0">Please Select One</option>
                <option value="7">Once a week</option>
                <option value="3.5">Twice a week</option>
                <option value="14">Every other week</option>
                <option value="4">DEMO</option>
            </select>
            <span></span>
        </div>

        <input type="submit" value="Add Seed" class="btn btn-light" />
        @* <button type="submit" formaction="@Url.Action("GetZone", "ZoneAPI")" class="btn btn-danger">Get Hardiness zone from api</button>*@
    </form>
    </body>

Views/Seed/AddSeedToBed.cshtml
@model Tracker.ViewModels.AddSeedViewModel

<h1>Add Seed to @Model.Bed.Name Garden Bed: </h1>
<body style="background-color: #D1CA08 ">
    <form asp-controller="Seed" asp-action="ProcessAddSeedToBed" method="post">
        <input type="hidden" value="@Model.Bed.Id" name="BedId" />

        <div class="form-group">
            <label asp-for="SeedId">Seed</label>

            <select asp-for="SeedId" asp-items="Model.Seeds"></select>

            <span asp-validation-for="SeedId"></span>
        </div>

        <input type="submit" value="Add Seed to Bed" class="btn btn-light" />
    </form>

    </body>

Views/Seed/AddSeedToWater.cshtml
@model Tracker.ViewModels.AddWaterSeedToBedViewModel

<h1>Add Seed to Garden Bed </h1>

<form asp-controller="Water" asp-action="AddWaterSeedToBed" method="post">

    <input type="hidden" value="@Model.BedId" name="BedId" />
   

    <div class="form-group">
        <label asp-for="SeedId">Seed</label>
         <select asp-for="SeedId" asp-items="Model.Seed"></select>
         <span asp-validation-for="SeedId"></span>
    </div>
 
    <div class="form-group">
        <label asp-for="DatePlanted">Date Planted</label>
        <input asp-for="DatePlanted" class="form-control" />
        <span></span>
    </div>

    <script>
      
      
    </script>

 
 

    <input type="submit" value="Add Seed to Bed" class="btn btn-danger" />
</form>

Views/Seed/Detail.cshtml
@model Tracker.ViewModels.SeedDetailViewModel

<h1>Seed Detail</h1>

<body style="background-color: #D1CA08 ">
    <table class="table">


        <b>Seed Name: </b>
        @Model.Name
        </br>
        <b>Hardiness Zone: </b> @Model.HardinessZone
        </br>
        <b>Date Watered: </b>
        @Model.DatePlanted
        <br />
        <b>Watering schedule: </b>
        every @Model.WaterSchedule days this needs to be watered
        </br>
        </br>
        <b>Garden Beds this seed is planted in: </b>
        @Model.BedText

    </table>

    <a asp-controller="Bed" asp-action="AddBedToSeed" asp-route-id="@Model.SeedId" class="btn btn-light">Add garden beds to this seed</a>
    </body>

Views/Seed/EditSeed 2.cshtml
@using Tracker.Models
@model List<Seed>

<h2>Edit Seeds</h2>

@if (Model.Count == 0)
{
    <p>No seeds selected for editing</p>
}
else
{
    <form asp-controller="Seed" asp-action="EditSeedSubmit" method="post">
        @foreach (var seed in Model)
        {
            <div>
                <h1>Bed: @seed.Name</h1>
                <label>Name:</label>
                <input type="text" name="seeds[]" value="@seed.Name" />
                <input type="text" name="datePlanted[]" value="@seed.DatePlanted" />
                <input type="text" name="hardinessZone[]" value="@seed.HardinessZone" />
                <input type="hidden" name="seedIds[]" value="@seed.Id" />
            </div>
        }
        <button type="submit" formaction="@Url.Action("EditSeedSubmit", "Seed")" class="btn btn-primary">Save Changes</button>

    </form>
}

Views/Seed/EditSeed.cshtml
@using Tracker.Models
@model List<Seed>

<h2>Edit Seeds</h2>
<body style="background-color: ##D1CA08 ">
    @if (Model.Count == 0)
    {
        <p>No seeds selected for editing</p>
    }
    else
    {
        <form asp-controller="Seed" asp-action="EditSeedSubmit" method="post">
            @foreach (var seed in Model)
            {
                <div>
                    <h1>Bed: @seed.Name</h1>
                    <label>Name:</label>
                    <input type="text" name="seeds[]" value="@seed.Name" />
                    <input type="text" name="hardinessZone[]" value="@seed.HardinessZone" />
                    <input type="text" name="datePlanted[]" value="@seed.DatePlanted" />

                    <input type="hidden" name="seedIds[]" value="@seed.Id" />
                </div>
            }
            <button type="submit" formaction="@Url.Action("EditSeedSubmit", "Seed")" class="btn btn-light">Save Changes</button>

        </form>
    }
    </body>

Views/Seed/Index.cshtml
@using Tracker.Models
@model List<Seed>

<form asp-controller="Seed" asp-action="Delete" method="post">
<div class="text-center">
    <h1>Current Seeds </h1>

@if (Model.Count == 0)
    {
       <p>No seeds have been created yet!</p>
    }
    else
    {
        if (Model != null) 
        {

        
        <table class="table">
         <tr>
         <th>Name</th>
         <th>Seed</th>
         <th>Delete</th>
         </tr>
        @foreach (var seed in Model)
         {
          <tr>
              <td>@seed.Id</td>

               <td>
                   <a asp-controller="Seed" asp-action="Detail" asp-route-id="@seed.Id">@seed.Name</a>     
               </td>

               <td>
                   <input type="checkbox" name="SeedIds" value="@seed.Id" />
               </td>
                    
                    
             </tr>
               
         }
            
       </table>
    }
    }


        </script>
        <p><a asp-controller="Seed" asp-action="Add" class="btn btn-danger">Add Seed</a></p>

        <button type="submit" formaction="@Url.Action("DeleteSeed", "Seed")" class="btn btn-danger">Delete Selected Seeds</button>


       
</form>